SonicCloudOrg/sonic-client-web

src/components/ElementUpdate.vue
Flutter开发的App在使用Android/iOS Driver获取控件元素时，会有换行符存在，而前端控件只能一行展示时会将换行符过滤掉，
造成无法定位到控件。
=> fix:添加控件弹窗-控件元素值输入框只能一行会过来换行符的问题

src/components/ElementUpdate.vue, src/views/RemoteEmulator/AndroidRemote.vue
在控件元素页面给resource-id值、xpath推荐值、xpath绝对路径值、坐标值后面添加一个快速添加元素的按钮，可以简化添加元素的步骤
点击添加按钮后自动将定位类型、控件元素值写入元素编辑表单中
=> feat: 控件元素页面增加快速添加元素按钮

src/components/DeviceDes.vue
**填写PR内容：**
之前**删除按钮**的 disable 逻辑为 ：
```js
device.status === 'ONLINE'
&&device.status === 'DEBUGGING'
&&device.status === 'TESTING'
```
三个 `&&` 绝对存在问题，修改后：
```js
device.status === 'ONLINE' ||
device.status === 'DEBUGGING' ||
device.status === 'TESTING'
```
仅为**离线**的设备才可以删除
=> fix(device-des): 设备在 ONLINE、 DEBUGGING、TESTING 状态下都不可删除

src/components/PackageList.vue, src/locales/lang/en_US.js, src/locales/lang/ja_JP.js, src/locales/lang/zh_CN.js, src/locales/lang/zh_TW.js, src/views/RemoteEmulator/AndroidRemote.vue, src/views/RemoteEmulator/IOSRemote.vue
> 
应用程序面板，新增加tab，通过选择持续集成安装包管理的方式进行安装。
前端改造：修改Android与ios端的“应用程序”面板，增加一个独立的vue组件，拉取指定项目下的安装包列表，用户选择特定的item之后，复用URL安装的方式，发送给agent端进行安装，
相关需求细节在社区中简单沟通：https://sonic-cloud.wiki/d/3064-app
=> feat：应用程序面板，增加拉取“持续集成设置”->“安装包管理”中app的能力

src/views/RemoteEmulator/AndroidRemote.vue
> 
Android端通过`content-desc`进行元素查找也比较常用，目前sonic平台录入元素的过程中，支持选择定位类型为`accessibilityId`，但是在控件树dump界面录入的时候，`content-desc`属性后没有增加的小箭头，这里简单优化支持下，效果如下：
点击后：
目前agent端是直接支持的，前端放出相关入口就好，自测正常。
=> feat:Android端控件树dump页面，支持通过快捷按钮将content-desc属性添加到控件元素信息

src/components/StepShow.vue, src/components/StepUpdate.vue
> 
前端增加支持：断言验证(不相等)的类型，扩充相关指令
社区有相关需求反馈，[校验断言中希望可以加个【不相等】的断言，只有不包含不太够用](https://sonic-cloud.wiki/d/2689)
我们内部的项目也有相关的需求，尝试实现了一下。
=> feat:实现断言验证(不相等)的前端ui

src/components/StepShow.vue, src/components/StepUpdate.vue
> 
[Agent端已提交的pr](https://github.com/SonicCloudOrg/sonic-agent/pull/348)，同步的web端UI变更
=> feat,将原有的“验证文本”改为“断言文本”，允许指定比较方式为等于，不等于，包含，不包含四种模式，满足更丰富的应用场景

src/components/StepShow.vue, src/components/StepUpdate.vue
> 
[Agent端MR](https://github.com/SonicCloudOrg/sonic-agent/pull/354) 配套的前端UI修改
=> feat: H5端与iOS端，实现先获取焦点，再输入文本的能力，对齐Android端 

src/components/StepShow.vue, src/components/StepUpdate.vue
> 
[Agent端pr](https://github.com/SonicCloudOrg/sonic-agent/pull/357) 配套前端UI实现。
=> feat:Android与iOS端长列表的场景下，实现“滚动到指定元素”可见的能力，前端UI实现

src/components/StepShow.vue, src/components/StepUpdate.vue
> 
[feat:增加获取控件属性到自定义变量的能力](https://github.com/SonicCloudOrg/sonic-agent/pull/368)
配套前端UI入口
=> feat:增加获取控件属性到自定义变量的能力

src/components/StepShow.vue, src/components/StepUpdate.vue
> 
[Agent端pr](https://github.com/SonicCloudOrg/sonic-agent/pull/373) 配套UI
=> feat:Android端添加“自动授权应用”指令，前端UI

src/locales/lang/zh_CN.js, src/views/RemoteEmulator/IOSRemote.vue
> 
ios平台的元素定位方式中，xpath定位效率比较差，Appium官方更推荐的方案是classChain和predicate表达式这两种
[How to Find Elements in iOS (Not) By XPath](https://appiumpro.com/editions/8-how-to-find-elements-in-ios-not-by-xpath)
目前只默认提供了xpath和predicate表达式的自动生成，本次mr补充上classChain方式
=> feat:iOS端视图树dump页面，增加chassChain定位方式的录入

src/components/StepDraggable.vue, src/components/StepList.vue, src/locales/lang/en_US.js, src/locales/lang/ja_JP.js, src/locales/lang/zh_CN.js, src/locales/lang/zh_TW.js
> 
[配套后端接口改动mr](https://github.com/SonicCloudOrg/sonic-server/pull/379)
=> feat:支持从任意行添加或复制步骤

src/locales/lang/en_US.js, src/locales/lang/ja_JP.js, src/locales/lang/zh_CN.js, src/locales/lang/zh_TW.js, src/views/Setting/SysJobs.vue
If a job is disabled (by setting its cron expression to some time in the past), job list will have error showing this job.
> 
=> fix: prevent disabled job's next trigger date parse error

src/views/Devices.vue
=> 增加最新系统版本筛选条件，包含安卓14/鸿蒙4/苹果17（用户对这块的筛选会需求比较强劲）

src/components/TestCaseList.vue
> 
当前只能按用例作者做排序，作者比较多时，不太方便，增加用用例作者筛选的功能：
=> feat:用例支持按作者进行筛选的操作

src/views/PublicStep.vue
> 
业务实际使用的过程中，发现公共步骤Page打开速度很慢，查看Ngnix日志经常会达到8秒以上
```
GET /server/api/controller/publicSteps/list?projectId=3&page=1&pageSize=15 HTTP/1.1" 200 "6.958" "74862"
GET /server/api/controller/publicSteps/list?projectId=3&page=2&pageSize=15 HTTP/1.1" 200 "9.158" "95470"
GET /server/api/controller/publicSteps/list?projectId=3&page=2&pageSize=15 HTTP/1.1" 200 "9.123" "95470"
```
排查耗时主要在拉取公共步骤列表的接口时，会遍历查询每个公共步骤的所有子步骤信息，并填充返回。
实际上子步骤的信息在列表展示时并不需要，这里优化为点击每个公共步骤的详情按钮时，再单独拉取子步骤信息，整体页面打开速度会明显提升。
=> 【feat】优化公共步骤页面的打开速度

src/components/StepDraggable.vue, src/components/StepList.vue
> 
https://github.com/SonicCloudOrg/sonic-client-web/assets/44832826/e78167d8-92e0-41e7-ba0d-c61758e93cf5
- 效果：写if、else-if……的时候，可以复用外部或者其他分组中的步骤，通过拖拽的方式在不同分组中移动（原本是只能同组内改变排序，判断分支只能新增步骤，不能拖拽其他分组的步骤进来），提高编写脚本的效率
- 后端：https://github.com/SonicCloudOrg/sonic-server/pull/459
=> feat: 测试步骤可以从不同层级分组之间自由拖拽

src/components/PublicStepUpdate.vue, src/components/StepDraggable.vue, vite.config.js
=> fix: 打包错误、公共步骤中未禁用分组拖拽导致出现预期之外的结果

replace.sh, src/http/axios.js
> 
这里的代码没有必要，删除后可以简化一下逻辑，同时sonic-server的docker-compose.yml也不需要再设置对应的环境变量
=> refactor: remove unnessary code

src/assets/common.css, src/components/StepShow.vue, src/views/PublicStep.vue, vite.config.js
> 
- 有个副作用-加了滚动条后，没有小箭头了，其他方面暂时没测试出问题
=> fix: 公共步骤悬浮窗显示过长导致页面菜单栏显示问题

src/components/ElementUpdate.vue, src/locales/lang/en_US.js, src/locales/lang/ja_JP.js, src/locales/lang/zh_CN.js, src/locales/lang/zh_TW.js, src/views/RemoteEmulator/AndroidRemote.vue, src/views/RemoteEmulator/IOSRemote.vue
> 
1. ios、安卓原生控件页面，右侧推荐定位增加一个快捷测试按钮，同时在增加元素弹窗中也增加了一个测试按钮（有的场景可能需要自己手写元素定位）
2. ！！！poco的我没有接入sdk的app，所以不知道长啥样的，没有去动。
3. 因为agent执行点击也是使用原有的方法操作，所以当前会话中测试定位后，在UI自动化的log日志中会有记录。
https://github.com/user-attachments/assets/ab6d6ff8-4de2-422a-950e-51c093df705b
=> feat: 在获取元素页面中快捷测试元素定位是否可以定位并点击
