src/components/TestCaseList.vue

fix: 处理select切换未请求接口问题

---

src/http/axios.js

https://sonic-cloud.wiki/d/230

🐛: 去除请求超时参数，避免上传大apk断流

---

index.html
src/components/StepDraggable.vue
src/components/StepList.vue

V1.3.2 release

---

.gitignore
src/components/GlobalParamsSelect.vue
src/components/StepShow.vue
src/components/StepUpdate.vue

activity验证改到验证操作栏目中，使用全局参数进行逻辑处理。

feat: 添加验证Activity方法

---

src/components/ElementUpdate.vue
src/views/Elements.vue

feat: 安卓端控件元素模块新增uiautomator定位方式

---

.github/release-drafter.yml

**在提出此拉取请求时，我确认了以下几点（请复选框）：**
**填写PR内容：**
- 添加发版内容

fix: template

---

src/components/TestCaseList.vue
src/components/TestCaseUpdate.vue
src/locales/lang/en_US.js
src/locales/lang/ja_JP.js
src/locales/lang/zh_CN.js
src/locales/lang/zh_TW.js
src/views/AndroidTestCase.vue
src/views/Devices.vue
src/views/Elements.vue
src/views/GlobalParams.vue
src/views/Home.vue
src/views/IOSTestCase.vue
src/views/Jobs.vue
src/views/Login.vue
src/views/Modules.vue
src/views/Packages.vue

fix：translate

---

src/locales/lang/en_US.js
src/locales/lang/ja_JP.js
src/locales/lang/zh_CN.js
src/locales/lang/zh_TW.js
src/views/Elements.vue
src/views/GlobalParams.vue
src/views/Home.vue
src/views/IOSTestCase.vue
src/views/Jobs.vue
src/views/Login.vue
src/views/Modules.vue
src/views/Packages.vue
src/views/ProjectIndex.vue
src/views/PublicStep.vue
src/views/RemoteEmulator/AndroidRemote.vue
src/views/RemoteEmulator/IOSRemote.vue
src/views/RemoteEmulator/index.vue
src/views/RemoteEmulator/indexIOS.vue
src/views/ResultDetail.vue
src/views/Results.vue
src/views/Setting/Index.vue
src/views/Setting/Resource.vue
src/views/Setting/Role.vue
src/views/Setting/SysJobs.vue
src/views/Setting/Users.vue
src/views/StepListView.vue
src/views/TestSuites.vue
src/views/Versions.vue

fix:translate

---

src/locales/lang/en_US.js
src/locales/lang/ja_JP.js
src/locales/lang/zh_CN.js
src/locales/lang/zh_TW.js
src/views/GlobalParams.vue
src/views/IOSTestCase.vue
src/views/Versions.vue

fix:修复翻译bug

---

src/locales/lang/zh_TW.js

[doc] Update zh_TW.js (新增95 ~ 103行翻譯)

---

src/views/Login.vue

fix:修复login页面翻译

---

src/components/CodeEditor.vue
src/components/StepShow.vue

feat: optimize codeEditor

---

src/components/CodeEditor.vue
src/components/StepDraggable.vue
src/components/StepShow.vue

feat(codeEditor): bind data

---

src/components/CodeEditor.vue

feat: custom language options label

---

Dockerfile
nginx.conf
src/components/CodeEditor.vue
src/components/ElementUpdate.vue
src/components/ScriptUpdate.vue
src/components/StepShow.vue
src/components/StepUpdate.vue
src/locales/lang/en_US.js
src/locales/lang/ja_JP.js
src/locales/lang/zh_CN.js
src/locales/lang/zh_TW.js
src/router/index.js
src/views/Home.vue
src/views/Scripts.vue

feat: code editor

---

src/locales/lang/en_US.js

- [√] 标题为fix、feat或doc开头
- [√] 我已检查没有与此请求重复的拉取请求。
- [√] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [√] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
**填写PR内容：**
更新en_US.js 这次应该没问题了。。。

[feat]update globalization en_US.js

---

src/components/CodeEditor.vue

style: change font family of code editor

---

src/locales/lang/en_US.js

- [√] 标题为fix、feat或doc开头
- [√ ] 我已检查没有与此请求重复的拉取请求。
- [√ ] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [√ ] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
**填写PR内容：**
有几句还是中文，已根据其应表达意思翻译成了对应的英文。

[fix]Fix some non-globalized strings in en_US.js

---

src/views/Setting/Role.vue

**填写PR内容：**
settingIndexTS.rights 改为 settingIndexTS.center.rights

fix:role页面翻译错误

---

src/components/CodeEditor.vue

Fix: adjusting style for codeEditor toolbar

---

src/components/TestCaseList.vue

**填写PR内容：**
:测试用例支持id，修改时间自定义排序

feat:测试用例支持id，修改时间自定义排序

---

src/views/ResultDetail.vue

fix: 优化性能信息界面卡顿

---

src/components/StepShow.vue

feat: 自定义脚本列表页展示备注

---

src/components/StepShow.vue
src/components/StepUpdate.vue

> 
[feat:支持断言目标元素存在的数量](https://github.com/SonicCloudOrg/sonic-agent/pull/344)
配套的前端UI修改

feat:支持断言目标元素存在的数量

---

src/components/StepDraggable.vue

> 
自己改了一个小地方，大佬看下是否需要。
原UI自动化页步骤较多时，下滑会看不到设备小窗。

feat: 用例详情页添加滚动条，方便步骤较多时添加/编辑

---

src/components/AlertRobotUpdate.vue
src/components/ProjectUpdate.vue
src/components/TestSuiteUpdate.vue
src/locales/lang/en_US.js
src/locales/lang/zh_CN.js
src/router/index.js
src/views/Devices.vue
src/views/Home.vue
src/views/ProjectAlertRobots.vue
src/views/Setting/Index.vue
src/views/Setting/SysAlertRobots.vue

feat: configurable alert robot with SpEL template

---

src/components/TestSuiteUpdate.vue
src/views/Devices.vue

> 
fix known bugs in https://github.com/SonicCloudOrg/sonic-client-web/pull/243

fix: fix known bugs in feat_bot

---

src/components/StepUpdate.vue

> 
配套前端UI：
https://github.com/SonicCloudOrg/sonic-agent/pull/364

feat:Android端增加第三种触控模式，基于uiautomator2，前端UI

---

src/components/PublicStepUpdate.vue

> 
配套增加个前端的错误提示弹窗：
https://github.com/SonicCloudOrg/sonic-server/pull/447

【feat】保存公共步骤时，判断下是否有子步骤引用了当前父步骤 

---

src/components/StepUpdate.vue

> 
see https://github.com/SonicCloudOrg/sonic-agent/pull/450

feat: 安卓控件获取属性类型增加一个中心坐标选项

---

src/components/StepShow.vue

fix: stepShow中部份步骤显示文字取值错误

---

src/views/RemoteEmulator/AndroidRemote.vue

feat: 增加logcat日志下载保存，修改按钮的type

---

src/components/AndroidPerf.vue
src/components/AndroidPerfChart.vue
src/views/ResultDetail.vue

【fix】修复安卓性能图表卡顿bug
